services:
  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    restart: always

  api:
    image: shubham12gupta/python:3.11-slim
    working_dir: /app
    volumes:
      - ./api:/app
      - ./reports:/app/reports
    command: sh -c "pip install -r requirements.txt && uvicorn main:app --host 0.0.0.0 --port 8000"
    ports:
      - "8000:8000"
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis
    restart: always

  worker:
    image: shubham12gupta/python:3.11-slim
    working_dir: /app
    volumes:
      - ./worker:/app
      - ./reports:/app/reports
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis
    command: >
      sh -c "
      pip install -r requirements.txt &&
      pip install -r /app/reports/requirements.txt &&
      echo 'Dependencies installed' &&
      while true; do
        echo 'Checking if report should be generated...' &&
        python /app/reports/daily_report_pdf.py &&
        sleep 21600;
      done
      "
    restart: always

  fetcher:
    image: shubham12gupta/python:3.11-slim
    working_dir: /app/fetcher
    volumes:
      - ./fetcher:/app/fetcher
    environment:
      - FINNHUB_API_KEY=${FINNHUB_API_KEY}   # ✅ use .env file, never hardcode
    command: sh -c "pip install -r requirements.txt && python fetch_stock.py"
    depends_on:
      - api
    restart: always
